
server:
  port: ${PORT:8080}

spring:
  application:
    name: JRTP-MiniProject01-CURDOperations
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update


plan:
  module:
    messages:
        save-success: Travel Plan is saved with id value
        save-failure: Travel plan is not saved with value
        find-by-id-failure: Travel plan is not found
        update-success: Travel Plan is updated
        update-failure: Travel plan is not found for updation
        delete-success: Travel Plan is deleted
        delete-failure: Travel plan is not found for deletion
        status-change-success: Travel Plan status is changed
        status-change-failure: Travel plan is not found for status change
